### ISSUE TITLE
Choleksy Huge Sparse Matrix

### ISSUE THREAD

**Issue by ncvescera** [Typing-Monkeys/BrunoLab#17]
Possiamo utilizzare le matrici sparse che dovrebbero contenere meno dati.
Il sito dove trovarle è https://sparse.tamu.edu/ 

Questo ha vari formati ma nessuno direttamente compatibile con python, però in SciPy c'è una funzione che è in grado di prendere un file `.mat` (matlab) e convertirlo in un dizionario utilizzabile in python (https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.loadmat.html)

## TODO

- [ ] Testare Cholesky e Gauss con matrici immense

**Comment by CristianCosci** [comment]
Io non aggiungerei la parte con le matrici sparse (non credo sia necessaria).
Ha per caso detto di implementarlo in cholesky o ci ha consigliato le matrici sparse per i futuri lavori?

**Comment by ncvescera** [comment]
> Ha per caso detto di implementarlo in cholesky o ci ha consigliato le matrici sparse per i futuri lavori?

Ci ha detto che per testare cholesky con matrici immense potevamo usare le matrici sparse dato che riescono ad essere immense, sono già generate da quel sito e pesano poco: la più grande (tipo 220mila righe e colonne) pesa nemmeno 1 GB.

Vogliamo quindi fare frega sega e lasciare sti dati che abbiamo già ??

**Comment by CristianCosci** [comment]
scrivo su telegram

**Comment by ncvescera** [comment]
Possiamo quindi confermare che queste modifiche non si faranno mai ?

**Comment by CristianCosci** [comment]
esattamente, non ci perderei tempo. Piuttosto farei una repo isolata con questo progetto (penso possa essere utile anche ad altri sfortunati che si imbatteranno in cholesky)

**Comment by ncvescera** [comment]
Perfetto !
Chiudo l'issue e poi ci organizzeremo per come fare la repo 🚀
